# Generated by Django 5.1.6 on 2025-03-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiBaiHat',
            fields=[
                ('loai_bai_hat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(help_text='Tên loại bài hát (Pop, Rock, Ballad,...)', max_length=255, unique=True)),
                ('mo_ta', models.TextField(blank=True, help_text='Mô tả về loại bài hát', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgheSi',
            fields=[
                ('nghe_si_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_nghe_si', models.CharField(max_length=255, unique=True)),
                ('tieu_su', models.TextField(blank=True, null=True)),
                ('anh_dai_dien', models.URLField(blank=True, null=True)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('quoc_gia', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
