# Generated by Django 5.1.6 on 2025-03-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihat',
            name='bai_hat_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baihatyeuthich',
            name='bai_hat_yeu_thich_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='danhsachphat',
            name='dach_sach_phat_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='goipremium',
            name='goi_premium_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lichsunghe',
            name='lich_su_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loibaihatdongbo',
            name='loi_dong_bo_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='nguoi_dung_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taixuong',
            name='tai_xuong_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='thanh_toan_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
