# Generated by Django 5.1.6 on 2025-03-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguoidung',
            name='gioi_tinh',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ')], default='male', max_length=10),
        ),
    ]
