# Generated by Django 5.1.6 on 2025-03-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_baihat_bai_hat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiBaiHat',
            fields=[
                ('loai_bai_hat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ten_loai', models.CharField(help_text='Tên loại bài hát (Pop, Rock, Ballad,...)', max_length=255, unique=True)),
                ('mo_ta', models.TextField(blank=True, help_text='Mô tả về loại bài hát', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
