# Generated by Django 4.2.10 on 2025-03-11 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_dach_sach_phat_id_danhsachphat_danh_sach_phat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BangXepHangBaiHat",
            fields=[
                (
                    "bang_xep_hang_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("loai_bang_xep_hang", models.CharField(max_length=50)),
                ("vi_tri", models.IntegerField()),
                ("gia_tri", models.IntegerField()),
                ("khoang_thoi_gian", models.CharField(max_length=20)),
                ("ngay_cap_nhat", models.DateTimeField(auto_now=True)),
                (
                    "bai_hat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.baihat"
                    ),
                ),
            ],
        ),
    ]
