# Generated by Django 5.1.6 on 2025-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_loaibaihat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danhsachphat',
            options={'ordering': ['so_thu_tu']},
        ),
        migrations.AddField(
            model_name='danhsachphat',
            name='anh_danh_sach',
            field=models.URLField(default='http://localhost:5173/uifaces-popular-image%20(1).jpg'),
        ),
        migrations.AddField(
            model_name='danhsachphat',
            name='so_nguoi_theo_doi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='danhsachphat',
            name='so_thu_tu',
            field=models.IntegerField(null=True),
        ),
    ]
