# Generated by Django 5.1.6 on 2025-03-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_nghesi_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
