<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-04-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_baihat_is_premium"),
        ("common", "0006_thanhtoan_is_active"),
    ]

    operations = []
=======
# Generated by Django 5.1.6 on 2025-04-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_baihat_is_premium"),
        ("common", "0006_thanhtoan_is_active"),
    ]

    operations = []
>>>>>>> 05e6804c972572fbbf9aa2d1d1eef55236f8a45a
