# Generated by Django 5.1.6 on 2025-04-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_merge_0006_baihat_is_premium_0006_thanhtoan_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baihat",
            name="is_premium",
        ),
    ]
