# Generated by Django 5.1.6 on 2025-04-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_remove_baihat_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="trang_thai_duyet",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Bị từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="baihat",
            name="trang_thai_duyet",
            field=models.CharField(
                choices=[
                    ("pending", "Chờ duyệt"),
                    ("approved", "Đã duyệt"),
                    ("rejected", "Bị từ chối"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
