# Generated by Django 5.1.6 on 2025-04-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_baihat_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
