# Generated by Django 5.1.6 on 2025-04-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_baihat_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="baihat",
            name="url_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
