# Generated by Django 5.1.6 on 2025-04-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_album_trang_thai_duyet_baihat_trang_thai_duyet"),
    ]

    operations = [
        migrations.AddField(
            model_name="nghesi",
            name="nguoi_dung",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nghe_si",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
