# Generated by Django 5.1.6 on 2025-04-11 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_nghesi_nguoi_dung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nghesi",
            name="nguoi_dung",
            field=models.ForeignKey(
                db_column="nguoi_dung_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cac_nghe_si",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
