# Generated by Django 5.1.6 on 2025-04-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_baihat_is_active"),
        ("common", "0011_alter_nghesi_nguoi_dung"),
    ]

    operations = []
