# Generated by Django 5.1.6 on 2025-04-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_baihat_url_image"),
        ("common", "0013_alter_album_trang_thai_duyet_and_more"),
    ]

    operations = []
