# Generated by Django 5.1.6 on 2025-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_merge_20250412_1613"),
    ]

    operations = [
        migrations.AddField(
            model_name="baihat",
            name="cam_xuc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vui", "Vui"),
                    ("buon", "Buồn"),
                    ("soi_dong", "Sôi động"),
                    ("tinh_yeu", "Tình yêu"),
                ],
                help_text="Cảm xúc của bài hát",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="danhsachphat",
            name="cam_xuc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vui", "Vui"),
                    ("buon", "Buồn"),
                    ("soi_dong", "Sôi động"),
                    ("tinh_yeu", "Tình yêu"),
                ],
                help_text="Cảm xúc của bài hát",
                max_length=50,
                null=True,
            ),
        ),
    ]
