# Generated by Django 5.1.6 on 2025-04-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_baihat_cam_xuc_danhsachphat_cam_xuc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baihat",
            name="cam_xuc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vui", "Vui"),
                    ("buon", "Buồn"),
                    ("soi_dong", "Sôi động"),
                    ("thu gian", "Thư giãn"),
                ],
                help_text="Cảm xúc của bài hát",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="danhsachphat",
            name="cam_xuc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vui", "Vui"),
                    ("buon", "Buồn"),
                    ("soi dong", "Sôi động"),
                    ("thu gian", "Thư giãn"),
                ],
                help_text="Cảm xúc của bài hát",
                max_length=50,
                null=True,
            ),
        ),
    ]
